In [46]:
import os
import pandas as pd

In [47]:
data20 = pd.read_csv("../raw_data/crime_data_2020.csv")
data20

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,apartment_office_prefix,apartment_number,location,watch,location_type,UC2_Literal,UCR_Number,neighborhood,npu,lat,long
0,200021209,1/2/2020,1/2/2020,15:21,1/2/2020,15:35,511.0,NaN,NaN,12 BROAD ST SW,Evening Watch,21.0,HOMICIDE,110,Downtown,M,33.75352,-84.39189
1,200061707,1/6/2020,1/6/2020,0:00,1/6/2020,18:25,109.0,NaN,NaN,785 PEYTON AVE NW,Evening Watch,NaN,HOMICIDE,110,Center Hill,J,33.77655,-84.46770
2,200100013,1/10/2020,1/9/2020,23:45,1/10/2020,0:00,110.0,NaN,NaN,1977 JONES AVE NW,Morning Watch,20.0,HOMICIDE,110,West Highlands,G,33.78738,-84.45208
3,200151818,1/16/2020,1/15/2020,17:15,1/15/2020,17:40,401.0,NaN,NaN,549 JOSEPH LOWERY BLVD,Evening Watch,99.0,HOMICIDE,110,West End,T,33.74001,-84.41782
4,200180440,1/18/2020,1/18/2020,3:31,1/18/2020,3:31,206.0,NaN,NaN,28 IRBY AVE NW,Morning Watch,13.0,HOMICIDE,110,South Tuxedo Park,B,33.84102,-84.38018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14826,202670466,9/23/2020,9/22/2020,18:00,9/23/2020,9:00,609.0,NaN,NaN,1207 HARDEE ST NE,Morning Watch,20.0,AUTO THEFT,730,Edgewood,O,33.75524,-84.34801
14827,202670717,9/23/2020,9/22/2020,21:30,9/23/2020,10:00,609.0,NaN,NaN,195 ARIZONA AVE NE,Day Watch,18.0,AUTO THEFT,730,Edgewood,O,33.75929,-84.33120
14828,202680455,9/24/2020,9/23/2020,23:00,9/24/2020,7:00,609.0,NaN,421,1661 LA FRANCE ST NE,Morning Watch,18.0,AUTO THEFT,730,Edgewood,O,33.76103,-84.33185
14829,202731007,9/29/2020,9/26/2020,18:00,9/29/2020,14:30,607.0,NaN,NaN,694 SCHUYLER AVE SE,Evening Watch,20.0,AUTO THEFT,730,Boulevard Heights,W,33.72520,-84.36533
14830,202731640,9/29/2020,9/29/2020,20:30,9/29/2020,21:00,504.0,NaN,NaN,768 MARIETTA ST NW,Evening Watch,18.0,AUTO THEFT,730,Marietta Street Artery,E,33.77331,-84.40403

In [48]:
crime_2020 = data20.drop(columns=['apartment_office_prefix', 'apartment_number','location_type','npu','watch'])
crime_2020

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,location,UC2_Literal,UCR_Number,neighborhood,lat,long
0,200021209,1/2/2020,1/2/2020,15:21,1/2/2020,15:35,511.0,12 BROAD ST SW,HOMICIDE,110,Downtown,33.75352,-84.39189
1,200061707,1/6/2020,1/6/2020,0:00,1/6/2020,18:25,109.0,785 PEYTON AVE NW,HOMICIDE,110,Center Hill,33.77655,-84.46770
2,200100013,1/10/2020,1/9/2020,23:45,1/10/2020,0:00,110.0,1977 JONES AVE NW,HOMICIDE,110,West Highlands,33.78738,-84.45208
3,200151818,1/16/2020,1/15/2020,17:15,1/15/2020,17:40,401.0,549 JOSEPH LOWERY BLVD,HOMICIDE,110,West End,33.74001,-84.41782
4,200180440,1/18/2020,1/18/2020,3:31,1/18/2020,3:31,206.0,28 IRBY AVE NW,HOMICIDE,110,South Tuxedo Park,33.84102,-84.38018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14826,202670466,9/23/2020,9/22/2020,18:00,9/23/2020,9:00,609.0,1207 HARDEE ST NE,AUTO THEFT,730,Edgewood,33.75524,-84.34801
14827,202670717,9/23/2020,9/22/2020,21:30,9/23/2020,10:00,609.0,195 ARIZONA AVE NE,AUTO THEFT,730,Edgewood,33.75929,-84.33120
14828,202680455,9/24/2020,9/23/2020,23:00,9/24/2020,7:00,609.0,1661 LA FRANCE ST NE,AUTO THEFT,730,Edgewood,33.76103,-84.33185
14829,202731007,9/29/2020,9/26/2020,18:00,9/29/2020,14:30,607.0,694 SCHUYLER AVE SE,AUTO THEFT,730,Boulevard Heights,33.72520,-84.36533
14830,202731640,9/29/2020,9/29/2020,20:30,9/29/2020,21:00,504.0,768 MARIETTA ST NW,AUTO THEFT,730,Marietta Street Artery,33.77331,-84.40403

In [49]:
data21 = pd.read_csv("../raw_data/crime_data_2021.csv")
#data21.head(2)

In [50]:
crime_2021 = data21.drop(columns=['occur_day','occur_day_num','zone','ibr_code','npu'])
crime_2021

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,location,UC2_Literal,neighborhood,lat,long
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,"1720 MARIETTA BLVD NW\nATLANTA, GA 30318\nUNIT...",LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,"300 PEACHTREE ST NE\nATLANTA, GA 30308\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,"229 COURTLAND ST NE\nATLANTA, GA 30303\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,"870 MAYSON TURNER RD NW\nATLANTA, GA 30314\nUN...",LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,"850 OAK ST SW\nATLANTA, GA 30310\nUNITED STATES",LARCENY-FROM VEHICLE,West End,33.740594,-84.415800
...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,"1099 SELWIN AVE SW\nATL, GA 30310\nUNITED STATES",BURGLARY,Oakland City,33.724966,-84.426435
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,"1144 ROSEDALE DR NE\nATLANTA, GA 30306\nUNITED...",LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,"141 HILLIARD ST SE\nATLANTA, GA 30312\nUNITED ...",BURGLARY,Sweet Auburn,33.750784,-84.376964
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,"180 JACKSON ST NE\nATLANTA, GA 30312\nUNITED S...",LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,"1162 PRYOR ST SW\nATL, GA 30315\nUNITED STATES",LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203

In [51]:
frames = [crime_2021,crime_2021]

new_crime = pd.concat(frames)
new_crime

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,location,UC2_Literal,neighborhood,lat,long
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,"1720 MARIETTA BLVD NW\nATLANTA, GA 30318\nUNIT...",LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,"300 PEACHTREE ST NE\nATLANTA, GA 30308\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,"229 COURTLAND ST NE\nATLANTA, GA 30303\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,"870 MAYSON TURNER RD NW\nATLANTA, GA 30314\nUN...",LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,"850 OAK ST SW\nATLANTA, GA 30310\nUNITED STATES",LARCENY-FROM VEHICLE,West End,33.740594,-84.415800
...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,"1099 SELWIN AVE SW\nATL, GA 30310\nUNITED STATES",BURGLARY,Oakland City,33.724966,-84.426435
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,"1144 ROSEDALE DR NE\nATLANTA, GA 30306\nUNITED...",LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,"141 HILLIARD ST SE\nATLANTA, GA 30312\nUNITED ...",BURGLARY,Sweet Auburn,33.750784,-84.376964
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,"180 JACKSON ST NE\nATLANTA, GA 30312\nUNITED S...",LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,"1162 PRYOR ST SW\nATL, GA 30315\nUNITED STATES",LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203

In [52]:
new_crime.to_csv("crime_20_21.csv", encoding='utf-8', index= False)