In [108]:
import os
import pandas as pd

In [109]:
data20 = pd.read_csv("../raw_data/crime_data_2020.csv")
data20

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,apartment_office_prefix,apartment_number,location,watch,location_type,UC2_Literal,UCR_Number,neighborhood,npu,lat,long
0,200021209,1/2/2020,1/2/2020,15:21,1/2/2020,15:35,511.0,NaN,NaN,12 BROAD ST SW,Evening Watch,21.0,HOMICIDE,110,Downtown,M,33.75352,-84.39189
1,200061707,1/6/2020,1/6/2020,0:00,1/6/2020,18:25,109.0,NaN,NaN,785 PEYTON AVE NW,Evening Watch,NaN,HOMICIDE,110,Center Hill,J,33.77655,-84.46770
2,200100013,1/10/2020,1/9/2020,23:45,1/10/2020,0:00,110.0,NaN,NaN,1977 JONES AVE NW,Morning Watch,20.0,HOMICIDE,110,West Highlands,G,33.78738,-84.45208
3,200151818,1/16/2020,1/15/2020,17:15,1/15/2020,17:40,401.0,NaN,NaN,549 JOSEPH LOWERY BLVD,Evening Watch,99.0,HOMICIDE,110,West End,T,33.74001,-84.41782
4,200180440,1/18/2020,1/18/2020,3:31,1/18/2020,3:31,206.0,NaN,NaN,28 IRBY AVE NW,Morning Watch,13.0,HOMICIDE,110,South Tuxedo Park,B,33.84102,-84.38018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14826,202670466,9/23/2020,9/22/2020,18:00,9/23/2020,9:00,609.0,NaN,NaN,1207 HARDEE ST NE,Morning Watch,20.0,AUTO THEFT,730,Edgewood,O,33.75524,-84.34801
14827,202670717,9/23/2020,9/22/2020,21:30,9/23/2020,10:00,609.0,NaN,NaN,195 ARIZONA AVE NE,Day Watch,18.0,AUTO THEFT,730,Edgewood,O,33.75929,-84.33120
14828,202680455,9/24/2020,9/23/2020,23:00,9/24/2020,7:00,609.0,NaN,421,1661 LA FRANCE ST NE,Morning Watch,18.0,AUTO THEFT,730,Edgewood,O,33.76103,-84.33185
14829,202731007,9/29/2020,9/26/2020,18:00,9/29/2020,14:30,607.0,NaN,NaN,694 SCHUYLER AVE SE,Evening Watch,20.0,AUTO THEFT,730,Boulevard Heights,W,33.72520,-84.36533
14830,202731640,9/29/2020,9/29/2020,20:30,9/29/2020,21:00,504.0,NaN,NaN,768 MARIETTA ST NW,Evening Watch,18.0,AUTO THEFT,730,Marietta Street Artery,E,33.77331,-84.40403

In [110]:
crime_2020 = data20.drop(columns=['apartment_office_prefix', 'apartment_number','location_type','npu','watch'])
crime_2020

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,location,UC2_Literal,UCR_Number,neighborhood,lat,long
0,200021209,1/2/2020,1/2/2020,15:21,1/2/2020,15:35,511.0,12 BROAD ST SW,HOMICIDE,110,Downtown,33.75352,-84.39189
1,200061707,1/6/2020,1/6/2020,0:00,1/6/2020,18:25,109.0,785 PEYTON AVE NW,HOMICIDE,110,Center Hill,33.77655,-84.46770
2,200100013,1/10/2020,1/9/2020,23:45,1/10/2020,0:00,110.0,1977 JONES AVE NW,HOMICIDE,110,West Highlands,33.78738,-84.45208
3,200151818,1/16/2020,1/15/2020,17:15,1/15/2020,17:40,401.0,549 JOSEPH LOWERY BLVD,HOMICIDE,110,West End,33.74001,-84.41782
4,200180440,1/18/2020,1/18/2020,3:31,1/18/2020,3:31,206.0,28 IRBY AVE NW,HOMICIDE,110,South Tuxedo Park,33.84102,-84.38018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14826,202670466,9/23/2020,9/22/2020,18:00,9/23/2020,9:00,609.0,1207 HARDEE ST NE,AUTO THEFT,730,Edgewood,33.75524,-84.34801
14827,202670717,9/23/2020,9/22/2020,21:30,9/23/2020,10:00,609.0,195 ARIZONA AVE NE,AUTO THEFT,730,Edgewood,33.75929,-84.33120
14828,202680455,9/24/2020,9/23/2020,23:00,9/24/2020,7:00,609.0,1661 LA FRANCE ST NE,AUTO THEFT,730,Edgewood,33.76103,-84.33185
14829,202731007,9/29/2020,9/26/2020,18:00,9/29/2020,14:30,607.0,694 SCHUYLER AVE SE,AUTO THEFT,730,Boulevard Heights,33.72520,-84.36533
14830,202731640,9/29/2020,9/29/2020,20:30,9/29/2020,21:00,504.0,768 MARIETTA ST NW,AUTO THEFT,730,Marietta Street Artery,33.77331,-84.40403

In [111]:
data21 = pd.read_csv("../raw_data/crime_data_2021.csv")
#data21.head(2)

In [112]:
crime_2021 = data21.drop(columns=['occur_day','occur_day_num','zone','ibr_code','npu'])
crime_2021.dtypes

offense_id        int64
rpt_date         object
occur_date       object
occur_time       object
poss_date        object
poss_time        object
beat              int64
location         object
UC2_Literal      object
neighborhood     object
lat             float64
long            float64
dtype: object

In [113]:
frames = [crime_2021,crime_2021]

new_crime = pd.concat(frames)
new_crime

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,location,UC2_Literal,neighborhood,lat,long
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,"1720 MARIETTA BLVD NW\nATLANTA, GA 30318\nUNIT...",LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,"300 PEACHTREE ST NE\nATLANTA, GA 30308\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,"229 COURTLAND ST NE\nATLANTA, GA 30303\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,"870 MAYSON TURNER RD NW\nATLANTA, GA 30314\nUN...",LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,"850 OAK ST SW\nATLANTA, GA 30310\nUNITED STATES",LARCENY-FROM VEHICLE,West End,33.740594,-84.415800
...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,"1099 SELWIN AVE SW\nATL, GA 30310\nUNITED STATES",BURGLARY,Oakland City,33.724966,-84.426435
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,"1144 ROSEDALE DR NE\nATLANTA, GA 30306\nUNITED...",LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,"141 HILLIARD ST SE\nATLANTA, GA 30312\nUNITED ...",BURGLARY,Sweet Auburn,33.750784,-84.376964
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,"180 JACKSON ST NE\nATLANTA, GA 30312\nUNITED S...",LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,"1162 PRYOR ST SW\nATL, GA 30315\nUNITED STATES",LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203

In [114]:
new_crime.dropna(how='any', inplace = True)
new_crime

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,location,UC2_Literal,neighborhood,lat,long
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,"1720 MARIETTA BLVD NW\nATLANTA, GA 30318\nUNIT...",LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,"300 PEACHTREE ST NE\nATLANTA, GA 30308\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,"229 COURTLAND ST NE\nATLANTA, GA 30303\nUNITED...",LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,"870 MAYSON TURNER RD NW\nATLANTA, GA 30314\nUN...",LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,"850 OAK ST SW\nATLANTA, GA 30310\nUNITED STATES",LARCENY-FROM VEHICLE,West End,33.740594,-84.415800
...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,"1099 SELWIN AVE SW\nATL, GA 30310\nUNITED STATES",BURGLARY,Oakland City,33.724966,-84.426435
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,"1144 ROSEDALE DR NE\nATLANTA, GA 30306\nUNITED...",LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,"141 HILLIARD ST SE\nATLANTA, GA 30312\nUNITED ...",BURGLARY,Sweet Auburn,33.750784,-84.376964
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,"180 JACKSON ST NE\nATLANTA, GA 30312\nUNITED S...",LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,"1162 PRYOR ST SW\nATL, GA 30315\nUNITED STATES",LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203

In [115]:

new_crime[['Address', 'City', 'Country']] = new_crime['location'].str.split('\n', n=2, expand = True)
new_crime
new_crime[['city','state','zipcode']] = new_crime['City'].str.split(' ', n=2, expand = True)
new_crime.head(4)

new_crime.drop(columns=['location','City'], inplace = True)
new_crime

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,UC2_Literal,neighborhood,lat,long,Address,Country,city,state,zipcode
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453,1720 MARIETTA BLVD NW,UNITED STATES,"ATLANTA,",GA,30318
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874,300 PEACHTREE ST NE,UNITED STATES,"ATLANTA,",GA,30308
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773,229 COURTLAND ST NE,UNITED STATES,"ATLANTA,",GA,30303
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631,870 MAYSON TURNER RD NW,UNITED STATES,"ATLANTA,",GA,30314
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,LARCENY-FROM VEHICLE,West End,33.740594,-84.415800,850 OAK ST SW,UNITED STATES,"ATLANTA,",GA,30310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,BURGLARY,Oakland City,33.724966,-84.426435,1099 SELWIN AVE SW,UNITED STATES,"ATL,",GA,30310
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806,1144 ROSEDALE DR NE,UNITED STATES,"ATLANTA,",GA,30306
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,BURGLARY,Sweet Auburn,33.750784,-84.376964,141 HILLIARD ST SE,UNITED STATES,"ATLANTA,",GA,30312
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614,180 JACKSON ST NE,UNITED STATES,"ATLANTA,",GA,30312
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203,1162 PRYOR ST SW,UNITED STATES,"ATL,",GA,30315

In [116]:
city = new_crime[new_crime['city'].str.contains("at", case=False)]
city_list = city['city'].to_list()
new_crime["city"].replace(city_list,"Atlanta",inplace=True)
new_crime

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,UC2_Literal,neighborhood,lat,long,Address,Country,city,state,zipcode
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453,1720 MARIETTA BLVD NW,UNITED STATES,Atlanta,GA,30318
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874,300 PEACHTREE ST NE,UNITED STATES,Atlanta,GA,30308
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773,229 COURTLAND ST NE,UNITED STATES,Atlanta,GA,30303
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631,870 MAYSON TURNER RD NW,UNITED STATES,Atlanta,GA,30314
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,LARCENY-FROM VEHICLE,West End,33.740594,-84.415800,850 OAK ST SW,UNITED STATES,Atlanta,GA,30310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,BURGLARY,Oakland City,33.724966,-84.426435,1099 SELWIN AVE SW,UNITED STATES,Atlanta,GA,30310
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806,1144 ROSEDALE DR NE,UNITED STATES,Atlanta,GA,30306
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,BURGLARY,Sweet Auburn,33.750784,-84.376964,141 HILLIARD ST SE,UNITED STATES,Atlanta,GA,30312
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614,180 JACKSON ST NE,UNITED STATES,Atlanta,GA,30312
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203,1162 PRYOR ST SW,UNITED STATES,Atlanta,GA,30315

In [117]:
new_crime["city"].value_counts()

Atlanta       26076
ADK,            210
HAPEVILLE,        6
Name: city, dtype: int64

In [118]:
new_crime["zipcode"].value_counts()

30318         3418
30310         1958
30309         1910
30308         1792
30315         1784
30312         1662
30303         1600
30324         1536
30305         1344
30314         1228
30331         1186
30313         1098
30311         1020
30307          896
30316          804
30306          726
30326          672
30354          398
30317          388
30363          238
30327          206
30342          204
30319           72
30344           22
30361            8
30336            8
30324-5018       6
30328            6
30339            4
30375            2
30380            2
30304            2
Name: zipcode, dtype: int64

In [119]:
new_crime = new_crime.loc[(new_crime['city'] == "Atlanta")]
new_crime

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,UC2_Literal,neighborhood,lat,long,Address,Country,city,state,zipcode
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453,1720 MARIETTA BLVD NW,UNITED STATES,Atlanta,GA,30318
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874,300 PEACHTREE ST NE,UNITED STATES,Atlanta,GA,30308
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773,229 COURTLAND ST NE,UNITED STATES,Atlanta,GA,30303
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631,870 MAYSON TURNER RD NW,UNITED STATES,Atlanta,GA,30314
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,LARCENY-FROM VEHICLE,West End,33.740594,-84.415800,850 OAK ST SW,UNITED STATES,Atlanta,GA,30310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,BURGLARY,Oakland City,33.724966,-84.426435,1099 SELWIN AVE SW,UNITED STATES,Atlanta,GA,30310
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806,1144 ROSEDALE DR NE,UNITED STATES,Atlanta,GA,30306
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,BURGLARY,Sweet Auburn,33.750784,-84.376964,141 HILLIARD ST SE,UNITED STATES,Atlanta,GA,30312
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614,180 JACKSON ST NE,UNITED STATES,Atlanta,GA,30312
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203,1162 PRYOR ST SW,UNITED STATES,Atlanta,GA,30315

In [120]:
new_crime["city"].value_counts()

Atlanta    26076
Name: city, dtype: int64

In [121]:
new_crime['zipcode'] = new_crime['zipcode'].str.split("-").str[0]
new_crime

C:\Users\vinoy\anaconda3\envs\Pythondata\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,UC2_Literal,neighborhood,lat,long,Address,Country,city,state,zipcode
0,21140096,5/20/2021,5/19/2021,15:20,5/19/2021,15:25,103,LARCENY-FROM VEHICLE,Hills Park,33.801693,-84.436453,1720 MARIETTA BLVD NW,UNITED STATES,Atlanta,GA,30318
1,21282015,8/6/2021,8/6/2021,22:23,8/6/2021,22:24,508,LARCENY-FROM VEHICLE,Downtown,33.762549,-84.387874,300 PEACHTREE ST NE,UNITED STATES,Atlanta,GA,30308
2,21320347,2/1/2021,1/31/2021,00:00,2/1/2021,06:53,509,LARCENY-FROM VEHICLE,Downtown,33.760759,-84.383773,229 COURTLAND ST NE,UNITED STATES,Atlanta,GA,30303
3,21791668,6/28/2021,6/27/2021,21:17,6/28/2021,20:00,102,LARCENY-NON VEHICLE,Vine City,33.755768,-84.416631,870 MAYSON TURNER RD NW,UNITED STATES,Atlanta,GA,30314
4,61583880,2/11/2021,2/11/2021,19:15,2/11/2021,20:29,401,LARCENY-FROM VEHICLE,West End,33.740594,-84.415800,850 OAK ST SW,UNITED STATES,Atlanta,GA,30310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14080,212230459,8/11/2021,8/10/2021,19:30,8/11/2021,07:30,403,BURGLARY,Oakland City,33.724966,-84.426435,1099 SELWIN AVE SW,UNITED STATES,Atlanta,GA,30310
14081,212230498,8/11/2021,8/2/2021,14:30,8/2/2021,16:00,601,LARCENY-NON VEHICLE,Virginia Highland,33.779969,-84.349806,1144 ROSEDALE DR NE,UNITED STATES,Atlanta,GA,30306
14082,212230549,8/11/2021,8/11/2021,09:21,8/11/2021,09:28,604,BURGLARY,Sweet Auburn,33.750784,-84.376964,141 HILLIARD ST SE,UNITED STATES,Atlanta,GA,30312
14083,212230568,8/11/2021,8/10/2021,21:40,8/11/2021,09:26,604,LARCENY-FROM VEHICLE,Sweet Auburn,33.759313,-84.375614,180 JACKSON ST NE,UNITED STATES,Atlanta,GA,30312
14084,212230651,8/11/2021,8/11/2021,09:00,8/11/2021,10:58,304,LARCENY-NON VEHICLE,Peoplestown,33.723348,-84.393203,1162 PRYOR ST SW,UNITED STATES,Atlanta,GA,30315

In [122]:
new_crime["zipcode"].value_counts()

30318    3418
30310    1958
30309    1910
30308    1792
30315    1784
30312    1662
30303    1600
30324    1542
30305    1344
30314    1228
30331    1186
30313    1098
30311    1020
30307     830
30316     746
30306     720
30326     672
30354     392
30317     314
30363     238
30327     206
30342     204
30319      72
30344      22
30361       8
30336       8
30328       6
30339       4
30375       2
30304       2
30380       2
Name: zipcode, dtype: int64

In [123]:
new_crime.to_csv("crime_20-21.csv", encoding='utf-8', index= False)

In [124]:
data10 = pd.read_csv("../raw_data/crime2.csv")
data10

C:\Users\vinoy\anaconda3\envs\Pythondata\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Report Number,Report Date,Occur Date,Occur Time,Possible Date,Possible Time,Beat,Apartment Office Prefix,Apartment Number,Location,Shift Occurence,Location Type,UCR Literal,UCR #,IBR Code,Neighborhood,NPU,Latitude,Longitude
0,90010930,"1,01,2009","1,01,2009",1145,"1,01,2009",1148.0,411.0,NaN,NaN,2841 GREENBRIAR PKWY,Day Watch,8,LARCENY-NON VEHICLE,630,2303,Greenbriar,R,33.68845,-84.49328
1,90011083,"1,01,2009","1,01,2009",1330,"1,01,2009",1330.0,511.0,NaN,NaN,12 BROAD ST SW,Day Watch,9,LARCENY-NON VEHICLE,630,2303,Downtown,M,33.75320,-84.39201
2,90011208,"1,01,2009","1,01,2009",1500,"1,01,2009",1520.0,407.0,NaN,NaN,3500 MARTIN L KING JR DR SW,Unknown,8,LARCENY-NON VEHICLE,630,2303,Adamsville,H,33.75735,-84.50282
3,90011218,"1,01,2009","1,01,2009",1450,"1,01,2009",1510.0,210.0,NaN,NaN,3393 PEACHTREE RD NE,Evening Watch,8,LARCENY-NON VEHICLE,630,2303,Lenox,B,33.84676,-84.36212
4,90011289,"1,01,2009","1,01,2009",1600,"1,01,2009",1700.0,411.0,NaN,NaN,2841 GREENBRIAR PKWY SW,Unknown,8,LARCENY-NON VEHICLE,630,2303,Greenbriar,R,33.68677,-84.49773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342908,193652089,"12,31,2019","12,31,2019",2030,"12,31,2019",2034.0,105.0,NaN,NaN,1385 SHARON ST NW,Morning Watch,20,AGG ASSAULT,420,1315K,Hunter Hills,K,33.75486,-84.43287
342909,193650336,"12,31,2019","12,31,2019",432,"12,31,2019",432.0,206.0,NaN,NaN,262 PHARR RD NE,Morning Watch,NaN,AGG ASSAULT,410,1314,Buckhead Village,B,33.83732,-84.37860
342910,193650603,"12,31,2019","12,31,2019",920,"12,31,2019",940.0,404.0,NaN,NaN,689 CASCADE AVE SW,Day Watch,18,AGG ASSAULT,410,1314,Westview,T,33.73636,-84.43680
342911,193651760,"12,31,2019","12,31,2019",1853,"12,31,2019",1900.0,404.0,NaN,NaN,763 CASCADE AVE SW,Evening Watch,26,AGG ASSAULT,410,1314,Westview,T,33.73483,-84.43750
342912,193652591,"12,31,2019","12,31,2019",2045,"12,31,2019",2055.0,406.0,NaN,NaN,237 PEYTON PL SW,Evening Watch,20,AGG ASSAULT,410,1314,Cascade Avenue/Road,S,33.72518,-84.45013

In [125]:
data10.dtypes

Report Number                int64
Report Date                 object
Occur Date                  object
Occur Time                   int64
Possible Date               object
Possible Time              float64
Beat                       float64
Apartment Office Prefix     object
Apartment Number            object
Location                    object
Shift Occurence             object
Location Type               object
UCR Literal                 object
UCR #                        int64
IBR Code                    object
Neighborhood                object
NPU                         object
Latitude                   float64
Longitude                  float64
dtype: object

In [126]:
test = data10.drop(columns=['Location Type'])
test

,Report Number,Report Date,Occur Date,Occur Time,Possible Date,Possible Time,Beat,Apartment Office Prefix,Apartment Number,Location,Shift Occurence,UCR Literal,UCR #,IBR Code,Neighborhood,NPU,Latitude,Longitude
0,90010930,"1,01,2009","1,01,2009",1145,"1,01,2009",1148.0,411.0,NaN,NaN,2841 GREENBRIAR PKWY,Day Watch,LARCENY-NON VEHICLE,630,2303,Greenbriar,R,33.68845,-84.49328
1,90011083,"1,01,2009","1,01,2009",1330,"1,01,2009",1330.0,511.0,NaN,NaN,12 BROAD ST SW,Day Watch,LARCENY-NON VEHICLE,630,2303,Downtown,M,33.75320,-84.39201
2,90011208,"1,01,2009","1,01,2009",1500,"1,01,2009",1520.0,407.0,NaN,NaN,3500 MARTIN L KING JR DR SW,Unknown,LARCENY-NON VEHICLE,630,2303,Adamsville,H,33.75735,-84.50282
3,90011218,"1,01,2009","1,01,2009",1450,"1,01,2009",1510.0,210.0,NaN,NaN,3393 PEACHTREE RD NE,Evening Watch,LARCENY-NON VEHICLE,630,2303,Lenox,B,33.84676,-84.36212
4,90011289,"1,01,2009","1,01,2009",1600,"1,01,2009",1700.0,411.0,NaN,NaN,2841 GREENBRIAR PKWY SW,Unknown,LARCENY-NON VEHICLE,630,2303,Greenbriar,R,33.68677,-84.49773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342908,193652089,"12,31,2019","12,31,2019",2030,"12,31,2019",2034.0,105.0,NaN,NaN,1385 SHARON ST NW,Morning Watch,AGG ASSAULT,420,1315K,Hunter Hills,K,33.75486,-84.43287
342909,193650336,"12,31,2019","12,31,2019",432,"12,31,2019",432.0,206.0,NaN,NaN,262 PHARR RD NE,Morning Watch,AGG ASSAULT,410,1314,Buckhead Village,B,33.83732,-84.37860
342910,193650603,"12,31,2019","12,31,2019",920,"12,31,2019",940.0,404.0,NaN,NaN,689 CASCADE AVE SW,Day Watch,AGG ASSAULT,410,1314,Westview,T,33.73636,-84.43680
342911,193651760,"12,31,2019","12,31,2019",1853,"12,31,2019",1900.0,404.0,NaN,NaN,763 CASCADE AVE SW,Evening Watch,AGG ASSAULT,410,1314,Westview,T,33.73483,-84.43750
342912,193652591,"12,31,2019","12,31,2019",2045,"12,31,2019",2055.0,406.0,NaN,NaN,237 PEYTON PL SW,Evening Watch,AGG ASSAULT,410,1314,Cascade Avenue/Road,S,33.72518,-84.45013